### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [bonzini/qboot#1]
I would like to point out that identifiers like "[`_IOPORT_H`](https://github.com/bonzini/qboot/blob/6bda70a1bb92f3aa67ae88c99e14f621c7e17158/include/ioport.h#L1)" and "[`_PCI_H`](https://github.com/bonzini/qboot/blob/6bda70a1bb92f3aa67ae88c99e14f621c7e17158/include/pci.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by bonzini** [comment]
Sure, patches to switch to e.g. `BIOS_IOPORT_H` are welcome.

**Comment by bonzini** [comment]
Fixed by commit 71f714a

**Comment by elfring** [comment]
Thanks for [your improvement](https://github.com/bonzini/qboot/commit/71f714aa968bf6b0fa811a59445a7fb3f9befc23 "Renaming of include guards") of affected include guards.

**Comment by elfring** [comment]
How do you think about to add another prefix to [more identifiers](https://github.com/bonzini/qboot/blob/71f714aa968bf6b0fa811a59445a7fb3f9befc23/include/const.h#L11 "Rename _AC and _AT?")?
