### ISSUE TITLE
using pflash cbfs.rom

### ISSUE THREAD

**Issue by sainath14** [bonzini/qboot#2]
When I tried to follow the commands in the readme to use cbfs, I get the following error

qemu-system-x86_64: -drive if=pflash,file=cbfs.rom,readonly=on: oversized backing file, pflash segments cannot be mapped under 00000000ff800000

**Comment by sainath14** [comment]
qemu-kvm -drive if=pflash,file=bios.bin,readonly=on \
        -drive if=pflash,file=cbfs.rom,readonly=on \
        -serial mon:stdio

pflash should not be used for bios.bin as that makes the total size of pflash exceed  8 MB limit.

**Comment by bonzini** [comment]
Fixed already, cbfs.rom must be 8128K.
