### ISSUE TITLE
eep! wont build.

### ISSUE THREAD

**Issue by JazzMaster** [bonzini/qboot#5]
missing a table?
main.o: In function `main':
/home/me/Desktop/code/qboot/main.c:82: undefined reference to`_GLOBAL_OFFSET_TABLE_'
code16.o: In function `e820_query_map':
/home/me/Desktop/code/qboot/code16.c:45: undefined reference to`_GLOBAL_OFFSET_TABLE_'
printf.o: In function `print_str':
/home/me/Desktop/code/qboot/printf.c:36: undefined reference to`_GLOBAL_OFFSET_TABLE_'
printf.o: In function `print_int':
/home/me/Desktop/code/qboot/printf.c:64: undefined reference to`_GLOBAL_OFFSET_TABLE_'
printf.o: In function `print_unsigned':
/home/me/Desktop/code/qboot/printf.c:99: undefined reference to`_GLOBAL_OFFSET_TABLE_'
printf.o:/home/me/Desktop/code/qboot/printf.c:141: more undefined references to `_GLOBAL_OFFSET_TABLE_' follow

**Comment by Erroneous1** [comment]
I got it to compile by adding:
`BIOS_CFLAGS += -fno-pic`
to line 11 of Makefile. IDK if Position Independent Code is needed here.

**Comment by bonzini** [comment]
What OS are you building it on?

**Comment by Erroneous1** [comment]
I was building on Arch Linux with gcc 6.2.1, running the 4.7.5-1-ARCH kernel (64 bit).

**Comment by fozog** [comment]
Got same issue and solved using @Erroneous1 patch.

I also would use  -mno-red-zone, not to solve a compile issue but to avoid messing with the stack in case qBoot want to handle exceptions or real IRQs in the future.

**Comment by bonzini** [comment]
Thanks, I'll apply the patch.

-mno-red-zone is not necessary because it only applies to 64-bit mode; 32-bit mode doesn't have a red zone.

**Comment by lostinblue** [comment]
I got the exact same issue in debian, I can build other kernels on this machine too x86_64. I can provide any additional details if necessary

**Comment by lostinblue** [comment]
Adding BIOS_CFLAGS += -fno-pic to the makefile did work for me too, should I go ahead and issue a pull request with this change?

**Comment by PRADEEPKJ** [comment]
I also had the same issue on "Linux ubuntu 4.12.0-rc7+ #2 SMP Thu Aug 10 05:57:30 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux". Adding BIOS_CFLAGS += -fno-pic fixed the issue.

**Comment by bonzini** [comment]
Fixed now.
