### ISSUE TITLE
Running on IncludeOS

### ISSUE THREAD

**Issue by fwsGonzo** [bonzini/qboot#6]
I really like this idea of custom simpler BIOS!
However, when running it with my 1.4mb IRCd image, I just get:

```
qemu-system-x86_64 --enable-kvm -kernel IRCd -device virtio-net,netdev=net0,mac=c0:01:0a:00:00:2a -netdev tap,id=net0,script=/home/gonzo/IncludeOS_install/etc/qemu-ifup -nographic -smp 1,sockets=1,cores=1,threads=1 -m 128 -cpu host -k en-us -realtime mlock=off -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -bios bios.bin
dma: command 8 not supported
```

The image is 32-bit. That might be the reason?

My IRC server repo is here: https://github.com/fwsGonzo/IRCd

For convenience here are the images:
http://fwsnet.net/kernels/IRCd http://fwsnet.net/kernels/IRCd.img (with  #bootloader)

The image I posted don't have any DMA code at all. 0x8 is DMA write, I think. We have a bootloader we can attach (second image) which loads the kernel with PIO.

**Comment by fwsGonzo** [comment]
Edit: After trying again a few times, it seems the dma command is just something corrupt
`dma: command 95 not supported`

random each time

**Comment by bonzini** [comment]
What version of QEMU are you running on?

**Comment by fwsGonzo** [comment]
```
$ qemu-system-x86_64 --version
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.5)
```

**Comment by fwsGonzo** [comment]
I am guessing that this is all because we don't have the new Qemu 2.7 which has the new DMA interface. Sadly, then we won't be able to use qboot, since we have to use whatever comes with the Ubuntu LTS (Qemu 2.5.0). Close?

**Comment by bonzini** [comment]
No, it should fall back just fine to the old fw_cfg interface.

**Comment by fwsGonzo** [comment]
Ok, I have verfied that the bios works well on qemu 2.7.0 with IncludeOS :)
