### ISSUE TITLE
Status and PCI related question

### ISSUE THREAD

**Issue by wkozaczuk** [bonzini/qboot#9]
Is this project still maintained? I would have post a message to proper emailing list but could not locate one. 

I have also come across the [NEMU project](https://github.com/intel/nemu) that mentions using qboot. Will qboot be eventually integrated into NEMU?

I noticed there is still [an open issue](https://github.com/bonzini/qboot/issues/5) that prevents it from compiling thought it is easily fixable by applying proper changes to makefile.

Also I have been trying to use qboot to speedup boot on [OSv unikernel](https://github.com/cloudius-systems/osv) on QEMU with qboot. I am encountering some PCI related issues that prevent me booting OSv with virtio-block or virtio-net devices. I only managed to boot OSv with ramfs with following setup:

qemu-system-x86_64 -m 2G -smp 1 -nographic \
 -bios ../qboot/bios.bin \
 -kernel kernel.elf \
 -enable-kvm -cpu host,+x2apic \
 -append "--console=serial /hello" \
 -gdb tcp::1234,server,nowait \
 -chardev stdio,mux=on,id=stdio,signal=off \
 -mon chardev=stdio,mode=readline \
 -device isa-serial,chardev=stdio

Once I add either block or networking device OSv fails to find the bar with index 2:

-device virtio-blk-pci,id=blk0,drive=hd0,scsi=off \
-drive file=usr.img,if=none,id=hd0,cache=none,aio=threads

**Comment by wkozaczuk** [comment]
Is my issue with BARs related or the same as reported here - https://github.com/bonzini/qboot/issues/7? If so does it mean that OS running on QEMU with qboot has to allocate bars itself? 
Out of curiosity does it mean that Linux is capable of doing it? Or as the example in readme suggests that Linux can only boot without PCI devices (like virtio-blk or virtio-net)?

**Comment by bonzini** [comment]
Yes, qboot does not attempt to allocate BARs, your issue is the same.

The project is maintained, but does not take need many changes. Firmware is boring, and qboot particularly so (by design).

I don't know what NEMU's plans are; last time I checked I didn't see any commit after the initial announcement.
